{
    "openapi": "3.0.0",
    "info": {
        "title": "API Back-End Sistema de Adoção de Animais",
        "description": "Esse API tem como objetivo ser o back-end do sistema de adoção de animais (SAA)",
        "version": "1.0.2"
    },
    "servers": [
        {
            "url": "http://localhost:5000/",
            "description": "API back-end"
        }
    ],
    "paths": {
        "/userDB/signup": {
            "post": {
                "summary": "Cadastro de usuário",
                "description": "Essa rota é responsável por cadastrar um novo usuário",
                "tags": ["Usuarios"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UsuarioCadastro"
                            },
                            "examples": {
                                "usuario": {
                                    "value": {
                                        "nome": "José Silva",
                                        "email": "jose@jose.com",
                                        "senha": "12345"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "500": {
                        "description": "User email alredy exist in data base"
                    },
                    "200": {
                        "description": "Registration Successful"
                    }
                }
            }
        },
        "/userDB/login": {
            "post": {
                "summary": "Login de usuário",
                "description": "Essa rota é responsável por autenticar um usuário",
                "tags": ["Usuarios"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UsuarioLogin"
                            },
                            "examples": {
                                "usuario": {
                                    "value": {
                                        "email": "jose@jose.com",
                                        "senha": "12345"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "Authorized"
                    }
                }
            }
        },
        "/userDB/logout": {
            "post": {
                "summary": "Logout de usuário",
                "description": "Essa rota é responsável por deslogar um usuário",
                "tags": ["Usuarios"],
                "responses": {
                    "401": {
                        "description": "Incompleto"
                    },
                    "200": {
                        "description": "Sucesso"
                    }
                }
            }
        },
        "/userDB/:id": {
            "put": {
                "summary": "Atualiza as informações do usuário",
                "description": "Essa rota é responsável por atualizar as infromações de um usuário",
                "tags": ["Usuarios"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UsuarioCadastro"
                            },
                            "examples": {
                                "usuario": {
                                    "value": {
                                        "nome": "José Saverino",
                                        "email": "jose@jose2000.com",
                                        "senha": "12345"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Concluido"
                    }
                }
            },
            "delete": {
                "summary": "Deleta usuário do banco de dados",
                "description": "Essa rota é responsável por deletar um usuário do banco de dados",
                "tags": ["Usuarios"],
                "responses": {
                    "200": {
                        "description": "Concluido"
                    }
                }
            }
        },
        "/favoriteAnimals/": {
            "post": {
                "summary": "Cria favoritos de usuário",
                "description": "Essa rota é responsável por criar a entry de animais favoritos de um usuário após ele ser cadastrado, a entry é composta pelo email do usuário e um array de animais vazio",
                "tags": ["Favoritos"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/EntryFavoritos"
                            },
                            "examples": {
                                "entry": {
                                    "value": {
                                        "email_usuario": "jose@jose.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }
            },
            "get": {
                "summary": "Captura os animais favoritos de um usuário",
                "description": "Essa rota é responsável por capturar os array de ids dos animais favoritos de um usuário através do email fornecido na página de login.",
                "tags": ["Favoritos"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/EntryFavoritos"
                            },
                            "examples": {
                                "entry": {
                                    "value": {
                                        "email_usuario": "jose@jose.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }
            }
        },
        "/favoriteAnimals/{email}": {
            "put": {
                "summary": "Altera ou deleta um animal na entry de favoritos de um usuário no Banco de Dados",
                "description": "Essa rota é responsável por adicionar ou remover um animal na entry de favoritos de um usuário, a operação realizada é definida através do operador que é passado nos parâmetros",
                "tags": ["Favoritos"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/EntryFavoritosPut"
                            },
                            "examples": {
                                "entry_add": {
                                    "value": {
                                        "animal_id": "66c9ced6891ceafea9333b27",
                                        "operation": "ADD"
                                    }
                                },
                                "entry_remove": {
                                    "value": {
                                        "animal_id": "66c9ced6891ceafea9333b27",
                                        "operation": "REMOVE"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }

            }
        },
        "/favoriteAnimals/modifyEmail": {
            "put": {
                "summary": "Altera o email do usuario na entry de favoritos do usuario",
                "description": "Recebe como parâmetros o email antigo e o email novo do usuário, a partir do antigo localiza a entry e atualiza para o email novo",
                "tags": ["Favoritos"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/EntryFavoritosEmailModify"
                            },
                            "examples": {
                                "modify_email": {
                                    "value": {
                                        "email_novo": "jose2004@jose2004.com",
                                        "email_velho": "josesantana@josesantana.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }
            }
        },
        "/favoriteAnimals/deleteEntry": {
            "post": {
                "summary": "Deleta a entry de animais favoritos de um usuário",
                "description": "Recebe como parâmetro o email do usuário, procura por um usuário no banco de dados com o mesmo email, extrai o id desse usuário, e deleta ele através do id",
                "tags": ["Favoritos"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/EntryFavoritosDelete"
                            },
                            "examples": {
                                "modify_email": {
                                    "value": {
                                        "email": "jose@jose.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    },
                    "500": {
                        "description": "Erro"
                    }
                }
            }
        },
        "/animals/": {
            "get": {
                "summary": "Coleta todos os animais",
                "description": "Coleta todos os animais do banco de dados e suas informações para passar para o front-end",
                "tags": ["Animais"],
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    },
                    "404": {
                        "description": "Erro"
                    }
                }
            },
            "post": {
                "summary": "Adiciona um novo animal",
                "description": "Adiciona o animal com suas informações no banco de dados",
                "tags": ["Animais"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Animal"
                            },
                            "examples": {
                                "add_animal": {
                                    "value": {
                                        "img": "ldjaslj@98e091830ndlq09023840230-1.png",
                                        "nome": "Caremelo",
                                        "tipo": "Cachorro",
                                        "porte": "Médio",
                                        "idade": "5 anos",
                                        "sexo": "Macho",
                                        "historia": "Caramelo brasileiro"

                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }
            }
        },
        "/animals/:id": {
            "get": {
                "summary": "Busca animal específico",
                "description": "Busca por um animal específico no banco de dados através do seu id",
                "tags": ["Animais"],
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    },
                    "404": {
                        "description": "Animal não encontrado"
                    }
                }
            },
            "delete": {
                "summary": "Deleta um animal específico",
                "description": "Deleta um animal específico no banco de dados através do seu id",
                "tags": ["Animais"],
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }
            },
            "put": {
                "summary": "Atualiza informações de um animal específico",
                "description": "Atualiza as informações de um animal específico no banco de dados através do seu id, atualizando pelas informações recebidas como parâmetros",
                "tags": ["Animais"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Animal"
                            },
                            "examples": {
                                "update_animal": {
                                    "value": {
                                        "img": "ldjaslj@98e091830ndlq09023840230-1.png",
                                        "nome": "Fila Brasileiro",
                                        "tipo": "Cachorro",
                                        "porte": "Grande",
                                        "idade": "3 anos",
                                        "sexo": "Macho",
                                        "historia": "Fila Brasileiro Bruto"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }
                
            }
        },
        "/adoption/": {
            "post": {
                "summary": "Grava registro de adoção",
                "description": "Grava o registro de adoção de um animal no banco de dados",
                "tags": ["Adoção"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Adoção"
                            },
                            "examples": {
                                "register_animal": {
                                    "value": {
                                        "animal_id": "66c9ced6891ceafea9333b27",
                                        "animal_nome": "Pitoco",
                                        "animal_idade": "5 anos",
                                        "animal_img": "ldjaslj@98e091830ndlq09023840230-1.png",
                                        "animal_tipo": "Cachorro",
                                        "animal_porte": "Pequeno",
                                        "animal_sexo": "Macho",
                                        "adotante_nome": "José",
                                        "adotante_cpf": "111.222.333-44",
                                        "adotante_rg": "3218721921-32",
                                        "adotante_email": "jose@jose.com",
                                        "adotante_idade": "41 anos",
                                        "adotante_cel": "(21)953300001",
                                        "pergunta1": "True",
                                        "pergunta2": "True",
                                        "pergunta3": "True",
                                        "pergunta4": "True",
                                        "pergunta5": "True",
                                        "status": "pending"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    }
                }
            },
            "get": {
                "summary": "Captura todos os registro de adoção",
                "description": "Captura todos os registros de adoção no banco de dados",
                "tags": ["Adoção"],
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    },
                    "404": {
                        "description": "Erro"
                    }
                }
            }
        },
        "/adoption/:id": {
            "get": {
                "summary": "Captura um único registro de adoção de um animal",
                "description": "Captura um único registro de adoção de animal através do id do registro de adoção",
                "tags": ["Adoção"],
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    },
                    "404": {
                        "description": "Erro"
                    }
                }
            },
            "put": {
                "summary": "Altera o status de um pedido de adoção de um animal",
                "description": "Altera o status de um pedido de adoção de um animal através do id do pedido",
                "tags": ["Adoção"],
                "requestBody": {
                    "content": {
                        "application/json":{
                            "schema":{
                                "$ref": "#/components/schemas/AdoçãoStatus"
                            }
                        },
                        "examples": {
                            "registro_aprovado": {
                                "value": {
                                    "status": "aprovado"
                                }
                            },
                            "register_reprovado": {
                                "value": {
                                    "status": "reprovado"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    },
                    "404": {
                        "description": "Erro"
                    }
                }
            },
            "delete": {
                "summary": "Deleta o pedido de adoção de um animal",
                "description": "Deleta o pedido de adoção de um animal do banco de dados através do id do pedido",
                "tags": ["Adoção"],
                "responses": {
                    "200": {
                        "description": "Sucesso"
                    },
                    "404": {
                        "description": "Erro"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "UsuarioCadastro": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "senha": {
                        "type": "string"
                    }
                }
            },
            "UsuarioLogin": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "senha": {
                        "type": "string"
                    }
                }
            },
            "EntryFavoritos": {
                "type": "object",
                "properties": {
                    "email_usuario": {
                        "type": "string"
                    },
                    "favorite_animals_array": {
                        "type": ["string"]
                    }
                }
            },
            "EntryFavoritosPut": {
                "type": "object",
                "properties": {
                    "animal_id": {
                        "type": "string"
                    },
                    "operacao": {
                        "type": "string"
                    }
                }
            },
            "EntryFavoritosEmailModify": {
                "type": "object",
                "properties": {
                    "email_antigo": {
                        "type": "string"
                    },
                    "email_novo": {
                        "type": "string"
                    }
                }
            },
            "EntryFavoritosDelete": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    }
                }
            },
            "Animal": {
                "type": "object",
                "properties": {
                    "img": {
                        "type": "url"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "tipo": {
                        "type": "string"
                    },
                    "porte": {
                        "type": "string"
                    },
                    "sexo": {
                        "type": "string"
                    },
                    "idade": {

                        "type": "string"
                    },
                    "historia": {
                        "type": "string"
                    }
                }
            },
            "Adoção": {
                "type": "object",
                "properties": {
                    "animal_id": {
                        "type": "string"
                    },
                    "animal_nome": {
                        "type": "string"
                    },
                    "animal_idade": {
                        "type": "string"
                    },
                    "animal_img": {
                        "type": "string"
                    },
                    "animal_tipo": {
                        "type": "string"
                    },
                    "animal_porte": {
                        "type": "string"
                    },
                    "animal_sexo": {
                        "type": "string"
                    },
                    "adotante_nome": {
                        "type": "string"
                    },
                    "adotante_cpf": {
                        "type": "string"
                    },
                    "adotante_rg": {
                        "type": "string"
                    },
                    "adotante_email": {
                        "type": "string"
                    },
                    "adotante_idade": {
                        "type": "string"
                    },
                    "adotante_cel": {
                        "type": "string"
                    },
                    "pergunta1": {
                        "type": "boolean"
                    },
                    "pergunta2": {
                        "type": "boolean"
                    },
                    "pergunta3": {
                        "type": "boolean"
                    },
                    "pergunta4": {
                        "type": "boolean"
                    },
                    "pergunta5": {
                        "type": "boolean"
                    },
                    "status": {
                        "type": "string"
                    }
                }
            },
            "AdoçãoStatus": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
